config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
    resources :habits do
      resources :habit_slots, only: [ :show, :new, :create,:edit, :update ]
    end
  resources :habit_slots, only: [:destroy]

  get "/dashboard", to: "pages#dashboard"

  patch '/habits/favourite/:id', to: 'habits#favourite'

  get "/setting", to: "pages#setting"

  get "/schedule_today/:date", to: "pages#schedule_today", as: "schedule_today"

  get "/schedule", to: "pages#schedule_day_dynamic", as: "schedule_day_dynamic"

  get "/calendar", to: "pages#calendar", as: "calendar"

  get "/progress_page", to: "pages#progress_page", as: "progress_page"
end

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="d-flex flex-column justify-content-center align-items-center">
        <blockquote class="blockquote">
          <p class="mb-0">"Your habits will determine your future"</p>
          <footer class="blockquote-footer">Jack Canfield</footer>
        </blockquote>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex flex-column justify-content-center align-items-center">
        <blockquote class="blockquote">
          <p class="mb-0">"Motivation is what gets you started, habit is what keeps you going."</p>
          <footer class="blockquote-footer">Jim Ryun</footer>
        </blockquote>
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-flex flex-column justify-content-center align-items-center">
        <blockquote class="blockquote">
          <p class="mb-0">"Habits are the compound interest of self-improvement"</p>
          <footer class="blockquote-footer">James Clear</footer>
        </blockquote>
      </div>
    </div>
  </div>
</div>

app/views/shared/_check.html.erb
<i class="fa-solid fa-check"></i>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= link_to "Habitracker", dashboard_path, class: "footer-title"%>
  <%# <h1 class="footer-title">Habitracker</h1> %>
  <%= link_to setting_path do %>
    <div class="footer-icon">
      <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
      <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
      </svg>
    </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
    <div>
      <%= link_to dashboard_path do %>
        <div class="navbar-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
          <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
          </svg>
        </div>
        <% end %>
    </div>
    <div>
      <%= link_to habits_path do %>
        <div class="navbar-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
          <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
          </svg>
        </div>
        <% end %>
    </div>
    <div>
      <%= link_to new_habit_path do %>
        <div class="navbar-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
          </svg>
        </div>
      <% end %>
    </div>
    <div>
      <%= link_to calendar_path do %>
        <div class="navbar-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-calendar-check-fill" viewBox="0 0 16 16">
          <path d="M4 .5a.5.5 0 0 0-1 0V1H2a2 2 0 0 0-2 2v1h16V3a2 2 0 0 0-2-2h-1V.5a.5.5 0 0 0-1 0V1H4V.5zM16 14V5H0v9a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2zm-5.146-5.146-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708.708z"/>
          </svg>
        </div>
      <% end %>
    </div>
    <div>
      <%= link_to progress_page_path do %>
        <div class="navbar-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-bar-chart-fill" viewBox="0 0 16 16">
          <path d="M1 11a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3zm5-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2z"/>
          </svg>
        </div>
      <% end %>
    </div>
</div>

app/views/shared/_simpleformhabitslots.html.erb
<body class="page">
  <%= render "shared/footer" %>
  <%= render "shared/navbar" %>
    <div class="container-form-habitslot">
      <h2 class= "habitslot-page-title">Change my habit day...</h2><hr>
      <%= simple_form_for [@habit, @habitslot] do |f| %>
        <div class="form-edit-habitslot">
          <%= f.input :start_time, html5:true, placeholder: "Start Date", label: "Start date" %>
          <%= f.input :end_time, html5:true, placeholder: "End Date", label: "End date" %>
          <div class="form-btns" style="display: flex; justify-content: space-between;">
            <%= f.submit "Done", class: "button-submit" %>
            <%= link_to habit_slot_path(@habitslot), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-button" do %>
              <div style= "margin-top: 8px;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                </svg>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
</body>

app/views/shared/_star.html.erb
<% if habit.favourite %>
  <i class="fa-solid fa-star fa-star-position favourite-toggle-colour"></i>
<% else %>
  <i class="fa-regular fa-star fa-star-position"></i>
<% end %>
<%# <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
<path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
</svg> %>