config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
    resources :habits do
      resources :habit_slots, only: [ :show, :new, :create,:edit, :update ]
    end
  resources :habit_slots, only: [:destroy]

  get "/dashboard", to: "pages#dashboard"

  patch '/habits/favourite/:id', to: 'habits#favourite'

  get "/setting", to: "pages#setting"

  get "/schedule_today/:date", to: "pages#schedule_today", as: "schedule_today"

  get "/schedule", to: "pages#schedule_day_dynamic", as: "schedule_day_dynamic"

  get "/calendar", to: "pages#calendar", as: "calendar"

  get "/progress_page", to: "pages#progress_page", as: "progress_page"
end

app/views/pages/_habit_card.html.erb
<li class="fav-habit-card" data-controller="completed" data-completed-target="habitslot" data-completed="<%= habitslot.completed %>" data-id="<%= habitslot.id %>" data-habit-id="<%= habitslot.habit_id %>">
  <p><%= habitslot.habit.title %></p><hr>
  <p><%= habitslot.habit.description %></p>
  <div data-action="click->completed#completed"><%= render "shared/check" %></div>
</li>

app/views/pages/_habit_card_favourite.html.erb
        <div data-controller="favourite">
          <li class="fav-habit-card" data-favourite-target="habit" data-favourite="<%= habit.favourite %>" data-id="<%= habit.id %>">
            <p><%= habit.title %></p><hr>
            <p><%= habit.description %></p>
            <div data-action="click->favourite#favourite" data-favourite-target="star"><%= render "shared/star", habit: habit %></div>
          </li>
        </div>

app/views/pages/_index_habit_card.html.erb
<%= link_to habit_path(habit) do %>
  <div data-controller="favourite">
    <div class="habit-card" style="background:linear-gradient(45deg, <%= habit.colour1 %>, <%= habit.colour2 %> );" data-favourite-target="habit" data-favourite="<%= habit.favourite %>" data-id="<%= habit.id %>">
      <p><%= habit.title %></p><hr>
      <div data-action="click->favourite#favourite" data-favourite-target="star"><%= render "shared/star", habit: habit %></div>
    </div>
  </div>
<% end %>

app/views/pages/calendar.html.erb
<body class="page">
<%= render "shared/footer" %>
<div class="content">
    <br>
    <%# monthly calendar where you're listing all habits for that person as a link to that habits show page %>

    <h1 class="cal">Calendar</h1>
    <div class="date-box">
        <%= month_calendar(events: @habitslots) do |date, habitslots| %>
        <% link_to schedule_today_path(date) do %>
          <%= date.day %>
        <% end %>
        <% end %>

    </div>
    <%= render "shared/navbar" %>

    <%# button to link to todays schedule %>
</div>
</body>

app/views/pages/dashboard.html.erb
<body class="page">
<%= render "shared/footer" %>
<br>
<div class="content">
    <div class="top-dash">
      <span>
        <% @date = Date.today %>
        <p><%= @date.strftime("%B, %d#{@date.day.ordinal}") %></p>
        <h1>Hello <%= current_user.nickname %></h1><hr>

        <br>
      </span><br>
    </div>
 <div class = "carousel-div">
  <%= render "shared/carousel" %>
 </div>
  <div>
    <h4 class= "fav-habit-title">My Favourite Habits</h4>
    <div class="fav-habit-display">
      <% @fav_habits.each do |habit| %>
          <li class="fav-habit-card" style="background:linear-gradient(45deg, <%= habit.colour1 %>, <%= habit.colour2 %> ); "data-favourite-target="habit" data-favourite="<%= habit.favourite %>" data-id="<%= habit.id %>">
            <%= link_to habit_path(habit) do %>
            <p class= "title-dashboard"><%= habit.title %></p><hr>
            <p class= "desc-dashboard"><%= habit.description %></p>
            <div data-action="click->favourite#favourite" data-favourite-target="star"><%= render "shared/star", habit: habit %></div>
            <% end %>
          </li>
      <% end %>
    </div>
  </div>
      </div>
    </div>
  <%= render "shared/navbar" %>
</div>
</body>

app/views/pages/home.html.erb
<body class='home-page'>


<div class="bg">
  <div class="container">
  <div class="header">
    <h1>Habitracker</h1>
  </div>
  <div class="quote">
    <p>Reach for the stars</p>
  </div>
  <div class="user_opt">
    <p><%= link_to "Sign In", new_user_session_path %></p>
    <p><%= link_to "Register", new_user_registration_path %></p>
  </div>
  </div>
</div>

</body>

app/views/pages/progress_page.html.erb
<body class="page">
  <%= render "shared/footer" %>
   <div class="back-button-progress">
      <%= link_to dashboard_path, style: "text-decoration: none" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-bar-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5ZM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5Z"/>
        </svg>
      <% end %>
      <%= link_to "Back", dashboard_path, style: "text-decoration: none"%>
    </div>



<div class= "container-progress">
<div>
<h2 class = "d-flex h2-progress-weekly" >My Progress</h2>
<p class = "info-text-progress">An overview of my completed habits by day</p>
</div><hr>

<div class= "chart-card">
  <div class="chart-wrapper">
    <%= column_chart @habits.map { |habit|
      {name: habit.title, data: habit.habit_slots.where(completed: true).group_by_day(:start_time).count }
      }, stacked: true, xtitle: "Day Completed", ytitle: "No. Habits Completed", color: ["black", "white", "purple", "orange"]
      %>
  </div>
</div>

  <div>
  <h2 class = "d-flex h2-progress-page" >My Overall Completion Rate</h2>
  <p class = "info-text-progress">Calculated completion rate across all habits</p>
  </div><hr>

  <div class="d-flex justify-content-center progress-circle progress-page-circle">
    <div data-controller="progress-circle" data-progress-circle-percent-value="<%= current_user.calculate_habit_completion_rate %>">
    </div>
  </div>
    <%= render "shared/navbar" %>

</div>
</body>

app/views/pages/schedule_today.html.erb
<body class="page">
  <div class="content">
    <h2><%= @date.strftime("%B, %d#{@date.day.ordinal}") %></h2>
    <h2>My Schedule Page</h2><br>

    <div class = "not-completed" data-wrapper="completed" style="transition: all 2s ease-in-out;">

    <% @habits.each do |habit| %>
      <% habit.habit_slots.each do |habitslot| %>
        <% if habitslot.start_time == @date %>
            <% habit = habitslot.habit %>
            <% if habitslot.completed == false %>
              <li class= "day-card" style="background:linear-gradient(45deg, <%= habit.colour1 %>, <%= habit.colour2 %> ); transition: all 2s ease-in-out;" data-controller="completed" data-id="<%= habitslot.id %>" data-habitid="<%= habit.id %>" data-date="<%= @date %>" data-completed="<%= habitslot.completed %>" >
              <%# <%= link_to habit_habit_slot_path(habitslot.habit, habitslot) do %>
                <div class="check" data-completed-target="habitslot" data-action="click->completed#completed">
                  <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="black" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                  </svg>
                </div>
              <%# <% end %>
                <div class="star-day"><%= render "shared/star", habit: habit%></div>
                <h5><%=habit.title %></h5>
                <div class="destroy-edit-buttons">
                  <%= link_to edit_habit_habit_slot_path(habitslot.habit, habitslot), class: "edit-button" do%>
                    <div class="icon-day">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="black" class="bi bi-pencil-square" viewBox="0 0 16 16">
                      <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                      <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg>
                    </div>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% end %>
        <% end %>
      <% end %>




    <%# button to change the date of this particular habitslot %>
    <%# <p class="btn btn-outline-primary"><%= link_to "change habit date", edit_habit_habit_slot_path(habitslot.habit, habitslot)%></p>
      <%# button to delete this particular habitslot %>
    <%# <p class="btn btn-outline-primary"><%= link_to "Delete", habit_slot_path(habitslot), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
    <%# <% end %>


    </div>

    <br><hr>

    <h3>Completed habits:</h3>
    <div class="completed" data-wrapper="completed" style="transition: all 2s ease-in-out;">
      <% @habits.each do |habit| %>
        <% habit.habit_slots.each do |habitslot| %>
          <% if habitslot.start_time == @date %>
              <% habit = habitslot.habit %>
            <% habit = habitslot.habit %>
            <% if habitslot.completed == true %>
              <li class= "day-card" style="background:linear-gradient(45deg, <%= habit.colour1 %>, <%= habit.colour2 %> );" data-controller="completed" data-id="<%= habitslot.id %>" data-habitid="<%= habit.id %>" data-date="<%= @date %>" data-completed="<%= habitslot.completed %>" >
                <div class="check" data-completed-target="habitslot" data-action="click->completed#completed">
                  <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="green" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                  </svg>
                </div>
                <div class="star-day"><%= render "shared/star", habit: habit%></div>
                <h5><%=habit.title %></h5>
                <div class="destroy-edit-buttons">
                  <%= link_to edit_habit_habit_slot_path(habitslot.habit, habitslot), class: "edit-button" do%>
                    <div>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                      <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                      <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg>
                    </div>
                  <% end %>
                </div>
              </li>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    </div>

    <%# button to link to broader calendar %>

  <%= render "shared/navbar" %>
  </div>
</body>

app/views/pages/setting.html.erb
<body class="settings-page">


<%= render "shared/navbar"%>
<%= render "shared/footer"%>
<div class="setting-image">
<div class="settings">
    <h1 class="settings-title"> <strong>Settings</strong></h1>
<%# <div class="button">
<a class="btn btn-primary" href="/camps/1122/challenges?path=06-Projects%2F04-Background-jobs"><strong>Privacy Policy</strong></a>
<a class="btn btn-primary" href="/camps/1122/challenges?path=06-Projects%2F04-Background-jobs"><strong>Terms of Services</strong></a>
<a class="btn btn-primary" href="/camps/1122/challenges?path=06-Projects%2F04-Background-jobs"><strong>Subcription Terms</strong></a>
<a class="btn btn-primary" href="/camps/1122/challenges?path=06-Projects%2F04-Background-jobs"><strong>Cancel Subscription</strong></a>
<a class="btn btn-primary" href="/camps/1122/challenges?path=06-Projects%2F04-Background-jobs"><strong>Log Out</strong></a> %>
<button class="cds-178 cds-149 cds-151 css-to9khb cds-160 cds-button-disableElevation card-settings" tabindex="0" type="submit" data-e2e="enroll-button" data-track="true" data-track-app="xdp_v1" data-track-page="xdp" data-track-action="[object Object]" data-track-component="enroll_button" style="background-color: rgb(232 229 219); color: rgb(31, 31, 31); font-weight: bold; border-color: transparent; height: 71px; width: 90%; margin:10px;"><span class="cds-150 cds-button-label"><div><span data-test="enroll-button-label">Privacy Policy</span><div class="startdate rc-StartDateString font-xs" data-test="start-date-string"></div></div></span></button>
<button class="cds-178 cds-149 cds-151 css-to9khb cds-160 cds-button-disableElevation card-settings" tabindex="0" type="submit" data-e2e="enroll-button" data-track="true" data-track-app="xdp_v1" data-track-page="xdp" data-track-action="[object Object]" data-track-component="enroll_button" style="background-color: rgb(232 229 219); color: rgb(31, 31, 31); font-weight: bold; border-color: transparent; height: 71px; width: 90%; margin:10px;"><span class="cds-150 cds-button-label"><div><span data-test="enroll-button-label">Terms of Services</span><div class="startdate rc-StartDateString font-xs" data-test="start-date-string"></div></div></span></button>
<%# <button class="cds-178 cds-149 cds-151 css-to9khb cds-160 cds-button-disableElevation card-settings" tabindex="0" type="submit" data-e2e="enroll-button" data-track="true" data-track-app="xdp_v1" data-track-page="xdp" data-track-action="[object Object]" data-track-component="enroll_button" style="background-color: rgb(232 229 219); color: rgb(31, 31, 31); font-weight: bold; border-color: transparent; height: 71px; width: 90%; margin:10px;"><span class="cds-150 cds-button-label"><div><span data-test="enroll-button-label">Subcription Terms</span><div class="startdate rc-StartDateString font-xs" data-test="start-date-string"></div></div></span></button>
<button class="cds-178 cds-149 cds-151 css-to9khb cds-160 cds-button-disableElevation card-settings" tabindex="0" type="submit" data-e2e="enroll-button" data-track="true" data-track-app="xdp_v1" data-track-page="xdp" data-track-action="[object Object]" data-track-component="enroll_button" style="background-color: rgb(232 229 219); color: rgb(31, 31, 31); font-weight: bold; border-color: transparent; height: 71px; width: 90%; margin:10px;"><span class="cds-150 cds-button-label"><div><span data-test="enroll-button-label">Cancel Subscription</span><div class="startdate rc-StartDateString font-xs" data-test="start-date-string"></div></div></span></button> %>
<button class="cds-178 cds-149 cds-151 css-to9khb cds-160 cds-button-disableElevation card-settings" tabindex="0" type="submit" data-e2e="enroll-button" data-track="true" data-track-app="xdp_v1" data-track-page="xdp" data-track-action="[object Object]" data-track-component="enroll_button" style="background-color: rgb(232 229 219); color: rgb(31, 31, 31); font-weight: bold; border-color: transparent; height: 71px; width: 90%; margin:10px;"><span class="cds-150 cds-button-label"><div><span data-test="enroll-button-label"><%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete}, style: "font-weight: bold"%></span><div class="startdate rc-StartDateString font-xs" data-test="start-date-string"></div></div></span></button>

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</body>