config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
    resources :habits do
      resources :habit_slots, only: [ :show, :new, :create,:edit, :update ]
    end
  resources :habit_slots, only: [:destroy]

  get "/dashboard", to: "pages#dashboard"

  patch '/habits/favourite/:id', to: 'habits#favourite'

  get "/setting", to: "pages#setting"

  get "/schedule_today/:date", to: "pages#schedule_today", as: "schedule_today"

  get "/schedule", to: "pages#schedule_day_dynamic", as: "schedule_day_dynamic"

  get "/calendar", to: "pages#calendar", as: "calendar"

  get "/progress_page", to: "pages#progress_page", as: "progress_page"
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  has_many :habit_slots, dependent: :destroy
  after_create :create_habit_slots
  after_update :update_habit_slots

  validates :title, :start_date, :end_date, presence: true


  def set_favourite(favourite)
    self.favourite = favourite.save
  end

  def weekdays
    @weekdays = []
    @weekdays << 1 if self.monday == true
    @weekdays << 2 if self.tuesday == true
    @weekdays << 3 if self.wednesday == true
    @weekdays << 4 if self.thursday == true
    @weekdays << 5 if self.friday == true
    @weekdays << 6 if self.saturday == true
    @weekdays << 0 if self.sunday == true
    @weekdays
  end

  def create_habit_slots
    dates = self.dates
    dates.each { |date| HabitSlot.create(habit_id: id, start_time: date) }
  end

  def update_habit_slots
    dates = self.dates
    habitslots = HabitSlot.where(habit_id: id)
    habitslots.each { |habitslot| habitslot.destroy }
    dates.each { |date| HabitSlot.create(habit_id: id, start_time: date) }
  end

  def dates
    dates = (start_date..end_date).to_a
    @filtered_dates = []
    dates.each do |date|
      weekdays.each { |weekday| @filtered_dates << date if weekday == date.wday }
    end
    @filtered_dates
  end

  def calculate_completed
    total_habitslots = HabitSlot.where(habit_id: id, user: current_user)
    completed_habitslots = HabitSlot.where(habit_id: id, user: current_user, completed: true)
    @habitslot_progress = completed_habitslots / total_habitslots
  end

  def calculate_habit_completion_rate_for_habit(id)
    habit = Habit.find(id)
    total_habitslots_count = habit.habit_slots.count
    completed_habitslots_count = 0
    habit.habit_slots.each do |habitslot|
        completed_habitslots_count += 1 if habitslot.completed == true
    end
    if total_habitslots_count > 0
      (completed_habitslots_count / total_habitslots_count) * 100
    else
      0
    end
  end

  def generategradient
    habit = Habit.find(id)
    @str = "lineargradient(90deg,#{habit.colour1}, #{habit.colour1});"
    @str
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :find_habit, only: %i[show edit update destroy favourite]

  def index
    @habits = Habit.where(user_id: current_user)
    @habitslots = []
    @habits.each do |habit|
      habit.habit_slots.each do |habitslot|
        @habitslots << habitslot
      end
    end
    if params[:query].present?
      @habits = Habit.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @habits = Habit.where(user_id: current_user)
    end
  end

  def show
    @habit = Habit.find(params[:id])
    @habit_completion_rate = @habit.calculate_habit_completion_rate_for_habit(params[:id])
    @total_habitslots_count = @habit.habit_slots.count
    @total_completed_habitslots_count = @habit.habit_slots.where(completed: true).count
  end

  def new
    @habit = Habit.new
  end

  def create
    @habit = Habit.create(habit_params)
    @habit.user_id = current_user.id
    # if @habit.repeat == true
    #   if @habit.everyday == true
    #     @habit.monday && @habit.tuesday && @habit.wednesday && @habit.thursday && @habit.friday && @habit.saturday && @habit.sunday = true
    #   end
    # elsif @habit.repeat == false
    #   @habit.everyday = false
    #   if @habit.monday == true
    #     @habit.tuesday && @habit.wednesday && @habit.thursday && @habit.friday && @habit.saturday && @habit.sunday = false
    #   end
    #   if @habit.tuesday == true
    #     @habit.monday && @habit.wednesday && @habit.thursday && @habit.friday && @habit.saturday && @habit.sunday = false
    #   end
    #   if @habit.wednesday == true
    #     @habit.monday && @habit.tuesday && @habit.thursday && @habit.friday && @habit.saturday && @habit.sunday = false
    #   end
    #   if @habit.thursday == true
    #     @habit.monday && @habit.tuesday && @habit.wednesday && @habit.friday && @habit.saturday && @habit.sunday = false
    #   end
    #   if @habit.friday == true
    #     @habit.monday && @habit.tuesday && @habit.wednesday && @habit.thursday && @habit.saturday && @habit.sunday = false
    #   end
    #   if @habit.saturday == true
    #     @habit.monday && @habit.tuesday && @habit.wednesday && @habit.thursday && @habit.friday && @habit.sunday = false
    #   end
    #   if @habit.sunday == true
    #     @habit.monday && @habit.tuesday && @habit.wednesday && @habit.thursday && @habit.friday && @habit.saturday = false
    #   end
    # end
    # @habit.save!
    if @habit.save
      redirect_to habits_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @habit.update(habit_params)
      redirect_to habit_path(@habit)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def favourite
    @habit.update(favourite_params)
  end

  def destroy
    # @habitslot = HabitSlot.find(params[:id])
    @habit = Habit.find(params[:id])
    @habit.destroy
    redirect_to habits_path, status: :see_other
  end

  private

  def favourite_params
    params.require(:habit).permit(:favourite)
  end

  def find_habit
    @habit = Habit.find(params[:id])
  end

  def habit_params
    params.require(:habit).permit(
      :title,
      :description,
      :favourite,
      :start_date,
      :end_date,
      :repeat,
      :everyday,
      :monday,
      :tuesday,
      :wednesday,
      :thursday,
      :friday,
      :saturday,
      :sunday,
      :user_id,
      :colour1,
      :colour2
    )
  end
end

app/views/habits/edit.html.erb
<body class="page">
  <%= render "shared/footer" %>
    <div class="form-container">
      <h1 class = "new-habit-title">New Habit...</h1>
      <div data-controller="form-toggler">
      <%= simple_form_for([@habit]) do |f| %>
        <div class="form-inputs">
          <%= f.input :title, label: false, placeholder: "Title" %>
          <%= f.input :description, label: false, placeholder: "Description" %>
          <%= f.input :start_date, html5:true, placeholder: "Start Date"%>
          <%= f.input :end_date, html5:true, placeholder: "End Date"%>
        </div>
        <div class="colour-picker-flexbox">
          <div data-controller="color-picker" class="color-picker-1">
            <%= f.input :colour1, as: :hidden, input_html: { value: "#1837C2", data: { color_picker_target: "input" } }  %>
            <p>Habit colour 1</p>
            <div data-color-picker-target="button"></div>
          </div>
          <div data-controller="color-picker">
            <%= f.input :colour2, as: :hidden, input_html: { value: "#9F7AEA", data: { color_picker_target: "input" } }  %>
            <p>Habit colour 2</p>
            <div data-color-picker-target="button"></div>
          </div>
        </div>
        <div data-action="change->form-toggler#toggleForm" data-form-toggler-target="repeat"><%= f.input :repeat, as: :boolean, label: "Make this a repeating habit", input_html: { class: "toggle" } %></div>
        <div class="d-none" data-controller="dateselect checkbox-select-all" data-form-toggler-target="inputs">
         <%# <div class="toggle">
            <input id="check-all" type="checkbox" data-action="change->checkbox-select-all#checkAll" data-checkbox-select-all-target="checkall">
            <label for="check-all">Do habit everyday</label>
          </div> %>
          <div class="weekdays">
            <%= f.input :monday, as: :boolean, label: content_tag(:span, "M"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :tuesday, as: :boolean, label: content_tag(:span, "T"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :wednesday, as: :boolean, label: content_tag(:span, "W"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :thursday, as: :boolean, label: content_tag(:span, "T"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :friday, as: :boolean, label: content_tag(:span, "F"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :saturday, as: :boolean, label: content_tag(:span, "S"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :sunday, as: :boolean, label: content_tag(:span, "S"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
          </div>
        </div>
        <%= f.submit "Add" %>
        <% end %>
    </div>
  <%= render "shared/navbar" %>
</body>

app/views/habits/index.html.erb
<body class="page">
  <%= render "shared/footer" %>
  <%= form_with url: habits_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "search",
      placeholder: "   search"
    %>
  <% end %>
  <hr>
  <div class="content">
    <div class="calendar">
      <h4>View daily schedules</h4>
      <%= week_calendar(events: @habitslots) do |date, habitslots| %>
        <% @habitslots.each do |habitslot| %>
          <div>
            <%= link_to schedule_today_path(date) do %>
              <h6><%= date.strftime("%a") %> <br> <%= date.strftime("%d") %></h6>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <hr>

  <div class="habits-display">
    <% @habits.each do |habit| %>
      <%= link_to habit_path(habit) do %>
        <div data-controller="favourite">
          <div class="habit-card" style="background:linear-gradient(45deg, <%= habit.colour1 %>, <%= habit.colour2 %> ); " data-favourite-target="habit" data-favourite="<%= habit.favourite %>" data-id="<%= habit.id %>">
            <p><%= habit.title %></p><hr>
            <div data-action="click->favourite#favourite" data-favourite-target="star"><%= render "shared/star", habit: habit %></div>
            <%# <div class="container-attributes">
              <div class="skills speed" style="width: <%= habit.calculate_habit_completion_rate_for_habit(habit.id)%">= habit.calculate_habit_completion_rate_for_habit(habit.id) %><%# </div>
            <%# </div>  %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>



          <%# <%= link_to habit_path(habit) do %>
            <%# <div class="habit-card"> %>
              <%# <div class="star-index"> %>

                <%# <%= render "shared/star", habit: habit %>

              <%# </div> %>
              <%# <h6><%= habit.title %>
            <%# </div>
          <% end %>
    <%# <% end %>
  <%# </div> %>



<%= render "shared/navbar" %>
</body>

app/views/habits/new.html.erb
<body class="page">
  <%= render "shared/footer" %>
    <div class="form-container">
      <h2 class = "new-habit-title">New Habit...</h2><hr>
      <div class= "form-info" data-controller="form-toggler" >
      <%= simple_form_for([@habit]) do |f| %>
        <div class="form-inputs">
          <%= f.input :title, label: false, placeholder: "Title" %>
          <%= f.input :description, label: false, placeholder: "Description" %>
          <%= f.input :start_date, html5:true, placeholder: "Start Date", input_html: { style: 'padding: 10px;' }%>
          <%= f.input :end_date, html5:true, placeholder: "End Date", input_html: { style: 'padding: 10px; display: flex; justify-content: space-evenly; flex-direction; column;' }%>
        </div>
        <div class= "toggle-style" data-action="change->form-toggler#toggleForm" data-form-toggler-target="repeat"><%= f.input :repeat, as: :boolean, label: "Repeat Habit", input_html: { class: "toggle" } %></div>
        <div class="d-none" data-controller="dateselect checkbox-select-all" data-form-toggler-target="inputs">
         <%# <div class="toggle">
            <input id="check-all" type="checkbox" data-action="change->checkbox-select-all#checkAll" data-checkbox-select-all-target="checkall">
            <label for="check-all">Do habit everyday</label>
          </div> %>
          <div class="weekdays">
            <%= f.input :monday, as: :boolean, label: content_tag(:span, "MON"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :tuesday, as: :boolean, label: content_tag(:span, "TUE"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :wednesday, as: :boolean, label: content_tag(:span, "WED"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :thursday, as: :boolean, label: content_tag(:span, "THU"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :friday, as: :boolean, label: content_tag(:span, "FRI"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :saturday, as: :boolean, label: content_tag(:span, "SAT"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
            <%= f.input :sunday, as: :boolean, label: content_tag(:span, "SUN"), label_html: { class: "wkday-icon day-label" }, input_html: { class: "day-checkbox", data: { checkbox_select_all_target: "checkbox" } } %>
          </div>
        </div><hr>
        <div class= "pick-color-title">
          <h6>Choose a colour scheme</h6>
        </div>
        <div class="colour-picker-flexbox">
          <div data-controller="color-picker" class="color-picker-1">
            <%= f.input :colour1, as: :hidden, input_html: { value: "#EC3344", data: { color_picker_target: "input" } }  %>
            <div data-color-picker-target="button"></div>
          </div>
          <div data-controller="color-picker">
            <%= f.input :colour2, as: :hidden, input_html: { value: "#FCBA56", data: { color_picker_target: "input" } }  %>
            <div data-color-picker-target="button"></div>
          </div>
        </div>
        <%= f.submit "Add Habit" %>
        <% end %>
    </div>
  <%= render "shared/navbar" %>
</body>

app/views/habits/show.html.erb
<div class="container-show">
  <%= render "shared/footer" %>
  <div class="habit-show">
    <div class="back-button">
      <%= link_to  habits_path, style: "text-decoration: none" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-bar-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5ZM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5Z"/>
        </svg>
      <% end %>
      <%= link_to "Back", habits_path, style: "text-decoration: none"%>
    </div>
    <div class="habit-card-show" style="background:linear-gradient(45deg, <%= @habit.colour1 %>, <%= @habit.colour2 %> );">
      <div class="starr"><%= render "shared/star", habit: @habit %></div>
      <div class="habit-card-details">
        <h2><%= @habit.title %></h2>
        <p><%= @habit.description %></p>
      </div>
    </div>
  </div>
    <div class="destroy-edit-buttons">
      <%= link_to edit_habit_path(@habit), class: "edit-button" do %>
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
          <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
          <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
        </div>
      <% end %>
      <%= link_to habit_path(@habit), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-button" do %>
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
          <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
          </svg>
        </div>
      <% end %>
    </div>
  <div class="complete-circle">
    <div
      data-controller="circularbar"
      data-circularbar-max-days-value="<%= @total_habitslots_count.to_i %>"
      data-circularbar-completion-days-value="<%=  @total_completed_habitslots_count.to_i%>"
      ></div>
  </div>
    <h3>So close to your goal !</h3>
    <%= render "shared/navbar" %>
</div>

<%# <%=  @habit_completion_rate %>